//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveLib.Ressources.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class english {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal english() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveLib.Ressources.Languages.english", typeof(english).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a valid option..
        /// </summary>
        internal static string home_showMenu_errorEnterValidOption {
            get {
                return ResourceManager.GetString("home_showMenu_errorEnterValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;jc&apos; =&gt; To create a new Job..
        /// </summary>
        internal static string home_showMenu_jc {
            get {
                return ResourceManager.GetString("home_showMenu_jc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;je&apos; =&gt; To execute a Job..
        /// </summary>
        internal static string home_showMenu_je {
            get {
                return ResourceManager.GetString("home_showMenu_je", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;jr&apos; =&gt; To remove a job.
        /// </summary>
        internal static string home_showMenu_jr {
            get {
                return ResourceManager.GetString("home_showMenu_jr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;ju&apos; =&gt; To update a job.
        /// </summary>
        internal static string home_showMenu_ju {
            get {
                return ResourceManager.GetString("home_showMenu_ju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;jv&apos; =&gt; To see all Job..
        /// </summary>
        internal static string home_showMenu_jv {
            get {
                return ResourceManager.GetString("home_showMenu_jv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press &apos;q&apos; to leave the program..
        /// </summary>
        internal static string home_showMenu_quitProgram {
            get {
                return ResourceManager.GetString("home_showMenu_quitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;s&apos; =&gt; Menu settings.
        /// </summary>
        internal static string home_showMenu_s {
            get {
                return ResourceManager.GetString("home_showMenu_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the option you want using the menu below : .
        /// </summary>
        internal static string home_showMenu_selectOption {
            get {
                return ResourceManager.GetString("home_showMenu_selectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome on EasySave !.
        /// </summary>
        internal static string home_showMenu_welcome {
            get {
                return ResourceManager.GetString("home_showMenu_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a destination path for the new Job : .
        /// </summary>
        internal static string jobCreate_newJob_enterDestPath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterDestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose if the job should be saved in differential or in full (Enter &apos;d&apos; or &apos;f&apos;) : .
        /// </summary>
        internal static string jobCreate_newJob_enterDifferentialOrFull {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterDifferentialOrFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a name for the new Job : .
        /// </summary>
        internal static string jobCreate_newJob_enterName {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a source path for the new Job : .
        /// </summary>
        internal static string jobCreate_newJob_enterSourcePath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is not a valid option..
        /// </summary>
        internal static string jobCreate_newJob_errorEnterDifferentialOrFull {
            get {
                return ResourceManager.GetString("jobCreate_newJob_errorEnterDifferentialOrFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The destination path is not valid..
        /// </summary>
        internal static string jobCreate_newJob_errorEnterValidDestPath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_errorEnterValidDestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a name that is not null or empty..
        /// </summary>
        internal static string jobCreate_newJob_errorEnterValidName {
            get {
                return ResourceManager.GetString("jobCreate_newJob_errorEnterValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source path is not valid..
        /// </summary>
        internal static string jobCreate_newJob_errorEnterValidSourcePath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_errorEnterValidSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter &apos;q&apos; to exit the job creation interface..
        /// </summary>
        internal static string jobCreate_newJob_exitMenu {
            get {
                return ResourceManager.GetString("jobCreate_newJob_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have enterred the Job creation portal..
        /// </summary>
        internal static string jobCreate_newJob_menuJobCreation {
            get {
                return ResourceManager.GetString("jobCreate_newJob_menuJobCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have enterred the Job creation portal..
        /// </summary>
        internal static string jobCreate_show_enterringJobCreation {
            get {
                return ResourceManager.GetString("jobCreate_show_enterringJobCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a number within the limit of the job list.
        /// </summary>
        internal static string jobRemove_chooseJob_errorChoice {
            get {
                return ResourceManager.GetString("jobRemove_chooseJob_errorChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which Job do you want to remove ?.
        /// </summary>
        internal static string jobRemove_chooseJob_WichJob {
            get {
                return ResourceManager.GetString("jobRemove_chooseJob_WichJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Job has been deleted !.
        /// </summary>
        internal static string jobRemove_endMessage_success {
            get {
                return ResourceManager.GetString("jobRemove_endMessage_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You don&apos;t have a Job yet!.
        /// </summary>
        internal static string jobRemove_error_jobListEmpty {
            get {
                return ResourceManager.GetString("jobRemove_error_jobListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job&apos;s number :.
        /// </summary>
        internal static string jobRemove_showJobs_id {
            get {
                return ResourceManager.GetString("jobRemove_showJobs_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have enterred the Job remove portal..
        /// </summary>
        internal static string jobRemove_showJobs_title {
            get {
                return ResourceManager.GetString("jobRemove_showJobs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job&apos;s destination path : .
        /// </summary>
        internal static string jobRun_chooseJob_dest {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is not a valid Job id..
        /// </summary>
        internal static string jobRun_chooseJob_errorEnterValidId {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_errorEnterValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID of Job : .
        /// </summary>
        internal static string jobRun_chooseJob_id {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Job.
        /// </summary>
        internal static string jobRun_chooseJob_listJobs {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_listJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job&apos;s name : .
        /// </summary>
        internal static string jobRun_chooseJob_name {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter the id of the Job you want : .
        /// </summary>
        internal static string jobRun_chooseJob_requestId {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_requestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job&apos;s source path : .
        /// </summary>
        internal static string jobRun_chooseJob_source {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job&apos;s type : .
        /// </summary>
        internal static string jobRun_chooseJob_type {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Differential.
        /// </summary>
        internal static string jobRun_chooseJob_typeDiff {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_typeDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full.
        /// </summary>
        internal static string jobRun_chooseJob_typeFull {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_typeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job in progress : .
        /// </summary>
        internal static string jobRun_progress_jobProgress {
            get {
                return ResourceManager.GetString("jobRun_progress_jobProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have enterred the Job execution portal..
        /// </summary>
        internal static string jobRun_show_enterringJobRun {
            get {
                return ResourceManager.GetString("jobRun_show_enterringJobRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is not a valid option (enter &apos;s&apos;, &apos;o&apos; or &apos;q&apos;)..
        /// </summary>
        internal static string jobRun_show_errorEnterValidOption {
            get {
                return ResourceManager.GetString("jobRun_show_errorEnterValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter &apos;q&apos; to quit the Job execution interface..
        /// </summary>
        internal static string jobRun_show_exitMenu {
            get {
                return ResourceManager.GetString("jobRun_show_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your option : .
        /// </summary>
        internal static string jobRun_show_requestOption {
            get {
                return ResourceManager.GetString("jobRun_show_requestOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to run all jobs sequentially (&apos;s&apos;) or just one job (&apos;o&apos;) ?.
        /// </summary>
        internal static string jobRun_show_selectOption {
            get {
                return ResourceManager.GetString("jobRun_show_selectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What Job do you want to change ?.
        /// </summary>
        internal static string jobUpdate_AskUpdate_WichJob {
            get {
                return ResourceManager.GetString("jobUpdate_AskUpdate_WichJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a number within the limit of the Job list.
        /// </summary>
        internal static string JobUpdate_ErrorMessage_Choice {
            get {
                return ResourceManager.GetString("JobUpdate_ErrorMessage_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press &apos;Enter&apos; to get back to the main menu.
        /// </summary>
        internal static string jobUpdate_exit_exitMenu {
            get {
                return ResourceManager.GetString("jobUpdate_exit_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have enterred the Job update interface.
        /// </summary>
        internal static string jobUpdate_ShowAll_EnterMessage {
            get {
                return ResourceManager.GetString("jobUpdate_ShowAll_EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Job : .
        /// </summary>
        internal static string jobUpdate_ShowAll_ListOfJobs {
            get {
                return ResourceManager.GetString("jobUpdate_ShowAll_ListOfJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job destination path :.
        /// </summary>
        internal static string jobUpdate_showJob_destPath {
            get {
                return ResourceManager.GetString("jobUpdate_showJob_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job name :.
        /// </summary>
        internal static string jobUpdate_showJob_nameJob {
            get {
                return ResourceManager.GetString("jobUpdate_showJob_nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job source path :.
        /// </summary>
        internal static string jobUpdate_showJob_sourcePath {
            get {
                return ResourceManager.GetString("jobUpdate_showJob_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose if the Job should be saved in differential or in full (Enter &apos;d&apos; or &apos;f&apos;) :.
        /// </summary>
        internal static string jobUpdate_updateJob_choiceDiffOrFull {
            get {
                return ResourceManager.GetString("jobUpdate_updateJob_choiceDiffOrFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The destination path is not valid..
        /// </summary>
        internal static string jobUpdate_updateJob_errorDestPathUnvalid {
            get {
                return ResourceManager.GetString("jobUpdate_updateJob_errorDestPathUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is not a valid option..
        /// </summary>
        internal static string jobUpdate_updateJob_errorInvalidOption {
            get {
                return ResourceManager.GetString("jobUpdate_updateJob_errorInvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a name that is not null or empty..
        /// </summary>
        internal static string jobUpdate_updateJob_errorNameNotNullOrEmpty {
            get {
                return ResourceManager.GetString("jobUpdate_updateJob_errorNameNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The source path is not valid..
        /// </summary>
        internal static string jobUpdate_updateJob_errorSourcePathUnvalid {
            get {
                return ResourceManager.GetString("jobUpdate_updateJob_errorSourcePathUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press &apos;Enter&apos; to exit the view menu..
        /// </summary>
        internal static string jobView_exit_exitMenu {
            get {
                return ResourceManager.GetString("jobView_exit_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Job&apos;s destionation path is : .
        /// </summary>
        internal static string jobView_show_destPath {
            get {
                return ResourceManager.GetString("jobView_show_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Job&apos;s name is : .
        /// </summary>
        internal static string jobView_show_nameJob {
            get {
                return ResourceManager.GetString("jobView_show_nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Job&apos;s source path is : .
        /// </summary>
        internal static string jobView_show_sourcePath {
            get {
                return ResourceManager.GetString("jobView_show_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have enterred the Job view portal..
        /// </summary>
        internal static string jobView_showAll_enterringJobView {
            get {
                return ResourceManager.GetString("jobView_showAll_enterringJobView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of Job : .
        /// </summary>
        internal static string jobView_showAll_listJob {
            get {
                return ResourceManager.GetString("jobView_showAll_listJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a langage : 1. French, 2. English.
        /// </summary>
        internal static string settings_showMenu_choiceLanguage {
            get {
                return ResourceManager.GetString("settings_showMenu_choiceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a format to modify: 1. Json, 2. Xml or &apos;q&apos; to exit the settings..
        /// </summary>
        internal static string settings_showMenu_choiceLogFormat {
            get {
                return ResourceManager.GetString("settings_showMenu_choiceLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose what you want to change (1. Language, 2. Log Format) : .
        /// </summary>
        internal static string settings_showMenu_choiceSettings {
            get {
                return ResourceManager.GetString("settings_showMenu_choiceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a valid choice.
        /// </summary>
        internal static string settings_showMenu_errorUnvalidChoice {
            get {
                return ResourceManager.GetString("settings_showMenu_errorUnvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current language : .
        /// </summary>
        internal static string settings_showMenu_stateLanguage {
            get {
                return ResourceManager.GetString("settings_showMenu_stateLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current log format : .
        /// </summary>
        internal static string settings_showMenu_stateLog {
            get {
                return ResourceManager.GetString("settings_showMenu_stateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Json enabled : .
        /// </summary>
        internal static string settings_showMenu_stateLogJson {
            get {
                return ResourceManager.GetString("settings_showMenu_stateLogJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Xml enabled : .
        /// </summary>
        internal static string settings_showMenu_stateLogXml {
            get {
                return ResourceManager.GetString("settings_showMenu_stateLogXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have enterred the Settings interface.
        /// </summary>
        internal static string settings_showMenu_welcomeMessage {
            get {
                return ResourceManager.GetString("settings_showMenu_welcomeMessage", resourceCulture);
            }
        }
    }
}
