//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveLib.Ressources.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class english {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal english() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveLib.Ressources.Languages.english", typeof(english).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a valid option.
        /// </summary>
        internal static string home_showMenu_errorEnterValidOption {
            get {
                return ResourceManager.GetString("home_showMenu_errorEnterValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;jc&apos; =&gt; To create a new Job.
        /// </summary>
        internal static string home_showMenu_jc {
            get {
                return ResourceManager.GetString("home_showMenu_jc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;je&apos; =&gt; To execute a Job.
        /// </summary>
        internal static string home_showMenu_je {
            get {
                return ResourceManager.GetString("home_showMenu_je", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;ju&apos; =&gt; To update a job.
        /// </summary>
        internal static string home_showMenu_ju {
            get {
                return ResourceManager.GetString("home_showMenu_ju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;jv&apos; =&gt; To see all Job.
        /// </summary>
        internal static string home_showMenu_jv {
            get {
                return ResourceManager.GetString("home_showMenu_jv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press &apos;q&apos; to leave the program.
        /// </summary>
        internal static string home_showMenu_quitProgram {
            get {
                return ResourceManager.GetString("home_showMenu_quitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;s&apos; =&gt; Menu settings.
        /// </summary>
        internal static string home_showMenu_s {
            get {
                return ResourceManager.GetString("home_showMenu_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please select the option you want using the menu below.
        /// </summary>
        internal static string home_showMenu_selectOption {
            get {
                return ResourceManager.GetString("home_showMenu_selectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome on EasySave !.
        /// </summary>
        internal static string home_showMenu_welcome {
            get {
                return ResourceManager.GetString("home_showMenu_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a destination path for the new Job.
        /// </summary>
        internal static string jobCreate_newJob_enterDestPath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterDestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a name for the new Job.
        /// </summary>
        internal static string jobCreate_newJob_enterName {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a source path for the new Job.
        /// </summary>
        internal static string jobCreate_newJob_enterSourcePath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have enterred the Job creation portal.
        /// </summary>
        internal static string jobCreate_show_enterringJobCreationI {
            get {
                return ResourceManager.GetString("jobCreate_show_enterringJobCreationI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à is running....
        /// </summary>
        internal static string jobRun_showEnd_isRunning {
            get {
                return ResourceManager.GetString("jobRun_showEnd_isRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job.
        /// </summary>
        internal static string jobRun_showEnd_job {
            get {
                return ResourceManager.GetString("jobRun_showEnd_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What job do you want to change ?.
        /// </summary>
        internal static string jobUpdate_AskUpdate_WichJob {
            get {
                return ResourceManager.GetString("jobUpdate_AskUpdate_WichJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter a number within the limit of the job list.
        /// </summary>
        internal static string JobUpdate_ErrorMessage_Choice {
            get {
                return ResourceManager.GetString("JobUpdate_ErrorMessage_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press &apos;Enter&apos; to get back to the main menu.
        /// </summary>
        internal static string jobUpdate_exit_exitMenu {
            get {
                return ResourceManager.GetString("jobUpdate_exit_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have enterred the Job update interface.
        /// </summary>
        internal static string jobUpdate_ShowAll_EnterMessage {
            get {
                return ResourceManager.GetString("jobUpdate_ShowAll_EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of jobs : .
        /// </summary>
        internal static string jobUpdate_ShowAll_ListOfJobs {
            get {
                return ResourceManager.GetString("jobUpdate_ShowAll_ListOfJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job destination path = .
        /// </summary>
        internal static string jobUpdate_showJob_destPath {
            get {
                return ResourceManager.GetString("jobUpdate_showJob_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job name = .
        /// </summary>
        internal static string jobUpdate_showJob_nameJob {
            get {
                return ResourceManager.GetString("jobUpdate_showJob_nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job source path = .
        /// </summary>
        internal static string jobUpdate_showJob_sourcePath {
            get {
                return ResourceManager.GetString("jobUpdate_showJob_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press any key to exit the view menu..
        /// </summary>
        internal static string jobView_exit_exitMenu {
            get {
                return ResourceManager.GetString("jobView_exit_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -----------------------------------.
        /// </summary>
        internal static string jobView_exit_space {
            get {
                return ResourceManager.GetString("jobView_exit_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Job&apos;s destionation path is :.
        /// </summary>
        internal static string jobView_show_destPath {
            get {
                return ResourceManager.GetString("jobView_show_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Job&apos;s name is :.
        /// </summary>
        internal static string jobView_show_nameJob {
            get {
                return ResourceManager.GetString("jobView_show_nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Job&apos;s source path is :.
        /// </summary>
        internal static string jobView_show_sourcePath {
            get {
                return ResourceManager.GetString("jobView_show_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -----------------------------------.
        /// </summary>
        internal static string jobView_show_space {
            get {
                return ResourceManager.GetString("jobView_show_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a langage : 1. French, 2. English.
        /// </summary>
        internal static string settings_showMenu_choiceLanguage {
            get {
                return ResourceManager.GetString("settings_showMenu_choiceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have enterred the Settings interface.
        /// </summary>
        internal static string settings_showMenu_welcomeMessage {
            get {
                return ResourceManager.GetString("settings_showMenu_welcomeMessage", resourceCulture);
            }
        }
    }
}
