//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveLib.Ressources.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class francais {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal francais() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveLib.Ressources.Languages.francais", typeof(francais).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de rentrer une option valide..
        /// </summary>
        internal static string home_showMenu_errorEnterValidOption {
            get {
                return ResourceManager.GetString("home_showMenu_errorEnterValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;jc&apos; =&gt; Pour créer un nouveau Job..
        /// </summary>
        internal static string home_showMenu_jc {
            get {
                return ResourceManager.GetString("home_showMenu_jc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;je&apos; =&gt; Pour exécuter un Job..
        /// </summary>
        internal static string home_showMenu_je {
            get {
                return ResourceManager.GetString("home_showMenu_je", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;jr&apos; =&gt; Pour supprimer un Job..
        /// </summary>
        internal static string home_showMenu_jr {
            get {
                return ResourceManager.GetString("home_showMenu_jr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;ju&apos; =&gt; Pour modifier un job.
        /// </summary>
        internal static string home_showMenu_ju {
            get {
                return ResourceManager.GetString("home_showMenu_ju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;jv&apos; =&gt; Pour voir tous les Job..
        /// </summary>
        internal static string home_showMenu_jv {
            get {
                return ResourceManager.GetString("home_showMenu_jv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyez sur &apos;q&apos; pour quitter le programme..
        /// </summary>
        internal static string home_showMenu_quitProgram {
            get {
                return ResourceManager.GetString("home_showMenu_quitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;s&apos; =&gt; Menu paramètres.
        /// </summary>
        internal static string home_showMenu_s {
            get {
                return ResourceManager.GetString("home_showMenu_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de sélectionner l&apos;option que vous souhaitez : .
        /// </summary>
        internal static string home_showMenu_selectOption {
            get {
                return ResourceManager.GetString("home_showMenu_selectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue sur EasySave !.
        /// </summary>
        internal static string home_showMenu_welcome {
            get {
                return ResourceManager.GetString("home_showMenu_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le chemin de destination du nouveau Job : .
        /// </summary>
        internal static string jobCreate_newJob_enterDestPath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterDestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir si le travail doit être sauvegardé en différentiel ou en entier (Entrez &apos;d&apos; ou &apos;f&apos;) : .
        /// </summary>
        internal static string jobCreate_newJob_enterDifferentialOrFull {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterDifferentialOrFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le nom du nouveau Job : .
        /// </summary>
        internal static string jobCreate_newJob_enterName {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le chemin de source du nouveau Job : .
        /// </summary>
        internal static string jobCreate_newJob_enterSourcePath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;option saisie n&apos;est pas valide..
        /// </summary>
        internal static string jobCreate_newJob_errorEnterDifferentialOrFull {
            get {
                return ResourceManager.GetString("jobCreate_newJob_errorEnterDifferentialOrFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin de la destination n&apos;est pas valide..
        /// </summary>
        internal static string jobCreate_newJob_errorEnterValidDestPath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_errorEnterValidDestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez un nom qui n&apos;est pas null ou vide..
        /// </summary>
        internal static string jobCreate_newJob_errorEnterValidName {
            get {
                return ResourceManager.GetString("jobCreate_newJob_errorEnterValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin de la source n&apos;est pas valide..
        /// </summary>
        internal static string jobCreate_newJob_errorEnterValidSourcePath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_errorEnterValidSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez &apos;q&apos; pour quitter l&apos;interface de création des Job..
        /// </summary>
        internal static string jobCreate_newJob_exitMenu {
            get {
                return ResourceManager.GetString("jobCreate_newJob_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous venez d&apos;accéder au portail de création des Job..
        /// </summary>
        internal static string jobCreate_newJob_menuJobCreation {
            get {
                return ResourceManager.GetString("jobCreate_newJob_menuJobCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous venez d&apos;accéder au portail de création des Job..
        /// </summary>
        internal static string jobCreate_show_enterringJobCreation {
            get {
                return ResourceManager.GetString("jobCreate_show_enterringJobCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer un nombre dans la limite de la liste de job..
        /// </summary>
        internal static string jobRemove_chooseJob_errorChoice {
            get {
                return ResourceManager.GetString("jobRemove_chooseJob_errorChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quel job souhaitez-vous supprimer ?.
        /// </summary>
        internal static string jobRemove_chooseJob_WichJob {
            get {
                return ResourceManager.GetString("jobRemove_chooseJob_WichJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le job a été supprimé !.
        /// </summary>
        internal static string jobRemove_endMessage_success {
            get {
                return ResourceManager.GetString("jobRemove_endMessage_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas encore de Job !.
        /// </summary>
        internal static string jobRemove_error_jobListEmpty {
            get {
                return ResourceManager.GetString("jobRemove_error_jobListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job numéro : .
        /// </summary>
        internal static string jobRemove_showJobs_id {
            get {
                return ResourceManager.GetString("jobRemove_showJobs_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous venez d&apos;accéder au portail de suppression des Job..
        /// </summary>
        internal static string jobRemove_showJobs_title {
            get {
                return ResourceManager.GetString("jobRemove_showJobs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin de destination du Job : .
        /// </summary>
        internal static string jobRun_chooseJob_dest {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_dest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce n&apos;est pas un identifiant de Job valide..
        /// </summary>
        internal static string jobRun_chooseJob_errorEnterValidId {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_errorEnterValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ID du Job : .
        /// </summary>
        internal static string jobRun_chooseJob_id {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Jobs :.
        /// </summary>
        internal static string jobRun_chooseJob_listJobs {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_listJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du Job : .
        /// </summary>
        internal static string jobRun_chooseJob_name {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer l&apos;identifiant de Job que vous souhaitez : .
        /// </summary>
        internal static string jobRun_chooseJob_requestId {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_requestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin source du Job : .
        /// </summary>
        internal static string jobRun_chooseJob_source {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type du Job : .
        /// </summary>
        internal static string jobRun_chooseJob_type {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentiel.
        /// </summary>
        internal static string jobRun_chooseJob_typeDiff {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_typeDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complet.
        /// </summary>
        internal static string jobRun_chooseJob_typeFull {
            get {
                return ResourceManager.GetString("jobRun_chooseJob_typeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job en cours de traitement : .
        /// </summary>
        internal static string jobRun_progress_jobProgress {
            get {
                return ResourceManager.GetString("jobRun_progress_jobProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous venez d&apos;accéder au portail d&apos;exécution des Job..
        /// </summary>
        internal static string jobRun_show_enterringJobRun {
            get {
                return ResourceManager.GetString("jobRun_show_enterringJobRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette option n&apos;est pas valide (entrez &apos;s&apos;, &apos;o&apos; ou &apos;q&apos;)..
        /// </summary>
        internal static string jobRun_show_errorEnterValidOption {
            get {
                return ResourceManager.GetString("jobRun_show_errorEnterValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez &apos;q&apos; pour quitter l&apos;interface d&apos;exécution des Job..
        /// </summary>
        internal static string jobRun_show_exitMenu {
            get {
                return ResourceManager.GetString("jobRun_show_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir votre option : .
        /// </summary>
        internal static string jobRun_show_requestOption {
            get {
                return ResourceManager.GetString("jobRun_show_requestOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous exécuter tous les Job séquentiellement (&apos;s&apos;) ou seulement un Job(&apos;o&apos;) ?.
        /// </summary>
        internal static string jobRun_show_selectOption {
            get {
                return ResourceManager.GetString("jobRun_show_selectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quel job souhaitez-vous modifier ?.
        /// </summary>
        internal static string jobUpdate_AskUpdate_WichJob {
            get {
                return ResourceManager.GetString("jobUpdate_AskUpdate_WichJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez entrer un nombre dans la limite de la liste de job..
        /// </summary>
        internal static string JobUpdate_ErrorMessage_Choice {
            get {
                return ResourceManager.GetString("JobUpdate_ErrorMessage_Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyez sur &apos;Entrée&apos; pour revenir au menu principal.
        /// </summary>
        internal static string jobUpdate_exit_exitMenu {
            get {
                return ResourceManager.GetString("jobUpdate_exit_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous venez d&apos;entrer dans le menu de modification de job..
        /// </summary>
        internal static string jobUpdate_ShowAll_EnterMessage {
            get {
                return ResourceManager.GetString("jobUpdate_ShowAll_EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste de jobs : .
        /// </summary>
        internal static string jobUpdate_ShowAll_ListOfJobs {
            get {
                return ResourceManager.GetString("jobUpdate_ShowAll_ListOfJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin de destination du job :.
        /// </summary>
        internal static string jobUpdate_showJob_destPath {
            get {
                return ResourceManager.GetString("jobUpdate_showJob_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du job :.
        /// </summary>
        internal static string jobUpdate_showJob_nameJob {
            get {
                return ResourceManager.GetString("jobUpdate_showJob_nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin source du job :.
        /// </summary>
        internal static string jobUpdate_showJob_sourcePath {
            get {
                return ResourceManager.GetString("jobUpdate_showJob_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de choisir entre une sauvegarde différentielle ou complète (entrer &apos;d&apos; ou &apos;f&apos;) :.
        /// </summary>
        internal static string jobUpdate_updateJob_choiceDiffOrFull {
            get {
                return ResourceManager.GetString("jobUpdate_updateJob_choiceDiffOrFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin de destination n&apos;est pas valide..
        /// </summary>
        internal static string jobUpdate_updateJob_errorDestPathUnvalid {
            get {
                return ResourceManager.GetString("jobUpdate_updateJob_errorDestPathUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option non valide.
        /// </summary>
        internal static string jobUpdate_updateJob_errorInvalidOption {
            get {
                return ResourceManager.GetString("jobUpdate_updateJob_errorInvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;entrer un nom qui n&apos;est ni nul ni vide.
        /// </summary>
        internal static string jobUpdate_updateJob_errorNameNotNullOrEmpty {
            get {
                return ResourceManager.GetString("jobUpdate_updateJob_errorNameNotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin de source n&apos;est pas valide..
        /// </summary>
        internal static string jobUpdate_updateJob_errorSourcePathUnvalid {
            get {
                return ResourceManager.GetString("jobUpdate_updateJob_errorSourcePathUnvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyez sur &apos;Entrée&apos; pour quitter le menu de visualisation..
        /// </summary>
        internal static string jobView_exit_exitMenu {
            get {
                return ResourceManager.GetString("jobView_exit_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin destination est : .
        /// </summary>
        internal static string jobView_show_destPath {
            get {
                return ResourceManager.GetString("jobView_show_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom du Job est : .
        /// </summary>
        internal static string jobView_show_nameJob {
            get {
                return ResourceManager.GetString("jobView_show_nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin source est : .
        /// </summary>
        internal static string jobView_show_sourcePath {
            get {
                return ResourceManager.GetString("jobView_show_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous venez d&apos;accéder au portail de visualisation des Jobs..
        /// </summary>
        internal static string jobView_showAll_enterringJobView {
            get {
                return ResourceManager.GetString("jobView_showAll_enterringJobView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Job : .
        /// </summary>
        internal static string jobView_showAll_listJob {
            get {
                return ResourceManager.GetString("jobView_showAll_listJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une langue : 1. Français, 2. Anglais.
        /// </summary>
        internal static string settings_showMenu_choiceLanguage {
            get {
                return ResourceManager.GetString("settings_showMenu_choiceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;entrer un choix valide..
        /// </summary>
        internal static string settings_showMenu_errorUnvalidChoice {
            get {
                return ResourceManager.GetString("settings_showMenu_errorUnvalidChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes dans l&apos;interface de paramètres..
        /// </summary>
        internal static string settings_showMenu_welcomeMessage {
            get {
                return ResourceManager.GetString("settings_showMenu_welcomeMessage", resourceCulture);
            }
        }
    }
}
