//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveLib.Ressources.Languages {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class francais {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal francais() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveLib.Ressources.Languages.francais", typeof(francais).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de rentrer une option valide .
        /// </summary>
        internal static string home_showMenu_errorEnterValidOption {
            get {
                return ResourceManager.GetString("home_showMenu_errorEnterValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;jc&apos; =&gt; Pour créer un nouveau Job.
        /// </summary>
        internal static string home_showMenu_jc {
            get {
                return ResourceManager.GetString("home_showMenu_jc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;je&apos; =&gt; Pour exécuter un Job.
        /// </summary>
        internal static string home_showMenu_je {
            get {
                return ResourceManager.GetString("home_showMenu_je", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;ju&apos; =&gt; Pour modifier un job.
        /// </summary>
        internal static string home_showMenu_ju {
            get {
                return ResourceManager.GetString("home_showMenu_ju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;je&apos; =&gt; Pour voir tous les Job.
        /// </summary>
        internal static string home_showMenu_jv {
            get {
                return ResourceManager.GetString("home_showMenu_jv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyez sur &apos;q&apos; pour quitter le programme .
        /// </summary>
        internal static string home_showMenu_quitProgram {
            get {
                return ResourceManager.GetString("home_showMenu_quitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;s&apos; =&gt; Menu paramètre.
        /// </summary>
        internal static string home_showMenu_s {
            get {
                return ResourceManager.GetString("home_showMenu_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci de sélectionner l&apos;option que vous souhaitez.
        /// </summary>
        internal static string home_showMenu_selectOption {
            get {
                return ResourceManager.GetString("home_showMenu_selectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue sur EasySave !.
        /// </summary>
        internal static string home_showMenu_welcome {
            get {
                return ResourceManager.GetString("home_showMenu_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le chemin de destination du nouveau Job.
        /// </summary>
        internal static string jobCreate_newJob_enterDestPath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterDestPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le nom du nouveau Job.
        /// </summary>
        internal static string jobCreate_newJob_enterName {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le chemin de source du nouveau Job.
        /// </summary>
        internal static string jobCreate_newJob_enterSourcePath {
            get {
                return ResourceManager.GetString("jobCreate_newJob_enterSourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous venez d&apos;accéder au portail de création des Job.
        /// </summary>
        internal static string jobCreate_show_enterringJobCreationI {
            get {
                return ResourceManager.GetString("jobCreate_show_enterringJobCreationI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en cours d&apos;exécution....
        /// </summary>
        internal static string jobRun_showEnd_isRunning {
            get {
                return ResourceManager.GetString("jobRun_showEnd_isRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Job.
        /// </summary>
        internal static string jobRun_showEnd_job {
            get {
                return ResourceManager.GetString("jobRun_showEnd_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Appuyer sur n&apos;importe quelle touche pour quitter le menu de visualisation.
        /// </summary>
        internal static string jobView_exit_exitMenu {
            get {
                return ResourceManager.GetString("jobView_exit_exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -----------------------------------.
        /// </summary>
        internal static string jobView_exit_space {
            get {
                return ResourceManager.GetString("jobView_exit_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin destination est :.
        /// </summary>
        internal static string jobView_show_destPath {
            get {
                return ResourceManager.GetString("jobView_show_destPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom du Job est :.
        /// </summary>
        internal static string jobView_show_nameJob {
            get {
                return ResourceManager.GetString("jobView_show_nameJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le chemin source est :.
        /// </summary>
        internal static string jobView_show_sourcePath {
            get {
                return ResourceManager.GetString("jobView_show_sourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à -----------------------------------.
        /// </summary>
        internal static string jobView_show_space {
            get {
                return ResourceManager.GetString("jobView_show_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisir une langue : 1. Français, 2. Anglais.
        /// </summary>
        internal static string settings_showMenu_choiceLanguage {
            get {
                return ResourceManager.GetString("settings_showMenu_choiceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes dans l&apos;interface de paramètres .
        /// </summary>
        internal static string settings_showMenu_welcomeMessage {
            get {
                return ResourceManager.GetString("settings_showMenu_welcomeMessage", resourceCulture);
            }
        }
    }
}
